// Asset audit. Scans every module's index.js for declareAssetReference()
// calls, cross-references against the files actually present in each
// module's assets/ folder, and writes docs/missing_assets.md.
//
// Run with: node scripts/audit-assets.mjs
// Run as part of npm run build via "prebuild".

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, statSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(here, '..');
const modulesDir = resolve(projectRoot, 'src/modules');
const docsDir = resolve(projectRoot, 'docs');

mkdirSync(docsDir, { recursive: true });

// A "declared reference" is a structured object we look for in source. We
// match declareAssetReference({...}) calls and pull moduleName / kind /
// assetKey / declaredFor out of the literal — works as long as the call
// uses literal strings, which our base module does.
const REFERENCE_REGEX = /declareAssetReference\s*\(\s*registry\s*,\s*\{([\s\S]*?)\}\s*\)/g;
const KEY_REGEX = (key) => new RegExp("(?:^|,|\\{)\\s*" + key + "\\s*:\\s*['\"`]([^'\"`]+)['\"`]", 'm');

function listModuleFolders() {
  if (!existsSync(modulesDir)) return [];
  return readdirSync(modulesDir).filter(name => {
    const path = join(modulesDir, name);
    if (!statSync(path).isDirectory()) return false;
    return existsSync(join(path, 'index.js'));
  });
}

function scanReferencesInModule(moduleName) {
  const indexPath = join(modulesDir, moduleName, 'index.js');
  const source = readFileSync(indexPath, 'utf8');
  const found = [];
  let match;
  while ((match = REFERENCE_REGEX.exec(source)) !== null) {
    const body = match[1];
    const moduleKey = KEY_REGEX('moduleName').exec(body)?.[1] ?? moduleName;
    const kind = KEY_REGEX('kind').exec(body)?.[1] ?? 'asset';
    const assetKey = KEY_REGEX('assetKey').exec(body)?.[1];
    const declaredFor = KEY_REGEX('declaredFor').exec(body)?.[1] ?? null;
    if (!assetKey) continue;
    found.push({ moduleName: moduleKey, kind, assetKey, declaredFor });
  }
  return found;
}

function listAssetsForModule(moduleName) {
  const assetsRoot = join(modulesDir, moduleName, 'assets');
  if (!existsSync(assetsRoot)) return new Set();
  const collected = new Set();
  function walk(directory, prefix) {
    for (const entry of readdirSync(directory)) {
      const path = join(directory, entry);
      const stats = statSync(path);
      if (stats.isDirectory()) walk(path, prefix + entry + '/');
      else collected.add(moduleName + '/' + prefix + entry);
    }
  }
  walk(assetsRoot, '');
  return collected;
}

// ── Gather + diff ──────────────────────────────────────────────────────────
const allDeclared = [];
const allPresent = new Set();
for (const moduleName of listModuleFolders()) {
  for (const reference of scanReferencesInModule(moduleName)) allDeclared.push(reference);
  for (const present of listAssetsForModule(moduleName)) allPresent.add(present);
}

const missing = allDeclared.filter(reference => !allPresent.has(reference.assetKey));

// ── Render markdown ───────────────────────────────────────────────────────
function renderMarkdown() {
  const lines = ['# Missing assets', ''];
  lines.push('_Generated by `scripts/audit-assets.mjs`. Drop files into the matching module\'s `assets/` folder to clear entries._');
  lines.push('');
  if (missing.length === 0) {
    lines.push('Every declared asset reference resolves. ');
    return lines.join('\n') + '\n';
  }
  const byModule = new Map();
  for (const reference of missing) {
    const list = byModule.get(reference.moduleName) ?? [];
    list.push(reference);
    byModule.set(reference.moduleName, list);
  }
  const moduleNames = Array.from(byModule.keys()).sort();
  for (const moduleName of moduleNames) {
    lines.push('## ' + moduleName);
    lines.push('');
    for (const reference of byModule.get(moduleName)) {
      const requestedBy = reference.declaredFor ? ' — requested by `' + reference.declaredFor + '`' : '';
      lines.push('- [' + reference.kind + '] `' + reference.assetKey + '`' + requestedBy);
    }
    lines.push('');
  }
  return lines.join('\n');
}

const outputPath = resolve(docsDir, 'missing_assets.md');
writeFileSync(outputPath, renderMarkdown());
console.log('wrote ' + outputPath + ' — ' + missing.length + ' missing asset(s)');
